version: "3"
services:
  postgres:
    image: "postgres:16.2-alpine"
    shm_size: 128mb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - "postgresdata:/var/lib/postgresql/data"

  tiny_note:
    build: .
    command: bash /app/start-dev.sh
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      MIX_ENV: "dev"
      DATABASE_HOST: "postgres"
    volumes:
      - .:/app

  livebook:
    image: ghcr.io/livebook-dev/livebook
    ports:
      - 8090:8090
      - 8091:8091
    depends_on:
      - tiny_note
    environment:
      LIVEBOOK_PORT: 8090
      LIVEBOOK_IFRAME_PORT: 8091
      LIVEBOOK_DEFAULT_RUNTIME: attached:tiny_note@tiny_note:magiccookie

volumes:
  postgresdata:
